# path
pretrained_model_name: "bert-base-uncased"
pretrained_cache_dir: "/home/shichao/share/pretrained_model"
checkpoint_file: "/home/shichao/project/sketched-nl2sql/saved_models/checkpoint.pt"
data_path: "/home/shichao/share/dataset/wikisql"

hidden_dim: 100
num_layers: 2
bidirectional: true
dropout: 0.3

# training settings
batch_size: 32
max_epoch: 20

seed: 1234
